version: '2'
services:
 dynamo-local:
   command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
   image: "amazon/dynamodb-local:latest"
   container_name: dynamo-local
   ports:
     - "8000:8000"
   volumes:
     - "./:/home/dynamodblocal/data"
   working_dir: /home/dynamodblocal