// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameChainMetric = "chain_metrics"

// ChainMetric mapped from table <chain_metrics>
type ChainMetric struct {
	UniqueDelegate    int32     `gorm:"column:unique_delegate" json:"unique_delegate"`
	Date              time.Time `gorm:"column:date;primaryKey" json:"date"`
	ChainName         string    `gorm:"column:chain_name;primaryKey" json:"chain_name"`
	UniqueDelegation  int32     `gorm:"column:unique_delegation" json:"unique_delegation"`
	UnbondedTokens    int64     `gorm:"column:unbonded_tokens" json:"unbonded_tokens"`
	BondedTokens      int64     `gorm:"column:bonded_tokens" json:"bonded_tokens"`
	MarketCap         int64     `gorm:"column:market_cap" json:"market_cap"`
	TotalSupply       int64     `gorm:"column:total_supply" json:"total_supply"`
	CirculatingSupply int64     `gorm:"column:circulating_supply" json:"circulating_supply"`
	Transactions      int64     `gorm:"column:transactions" json:"transactions"`
	BlockTime         string    `gorm:"column:block_time" json:"block_time"`
	Inflation         string    `gorm:"column:inflation" json:"inflation"`
	StakingApr        string    `gorm:"column:staking_apr" json:"staking_apr"`
	TxsPerBlock       string    `gorm:"column:txs_per_block" json:"txs_per_block"`
	CommunityPool     int64     `gorm:"column:community_pool" json:"community_pool"`
	BlockHeight       int64     `gorm:"column:block_height" json:"block_height"`
	TotalStake        int64     `gorm:"column:total_stake" json:"total_stake"`
}

// TableName ChainMetric's table name
func (*ChainMetric) TableName() string {
	return TableNameChainMetric
}
