// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCoinPrice = "coin_price"

// CoinPrice mapped from table <coin_price>
type CoinPrice struct {
	Date      time.Time `gorm:"column:date;primaryKey" json:"date"`
	Price     string    `gorm:"column:price" json:"price"`
	Symbol    string    `gorm:"column:symbol" json:"symbol"`
	ChainName string    `gorm:"column:chain_name;primaryKey" json:"chain_name"`
}

// TableName CoinPrice's table name
func (*CoinPrice) TableName() string {
	return TableNameCoinPrice
}
