// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMultisigAccount = "multisig_account"

// MultisigAccount mapped from table <multisig_account>
type MultisigAccount struct {
	Address    string    `gorm:"column:address;primaryKey" json:"address"`
	Name       string    `gorm:"column:name" json:"name"`
	Threshold  int32     `gorm:"column:threshold;not null" json:"threshold"`
	ChainName  string    `gorm:"column:chain_name;not null" json:"chain_name"`
	Members    string    `gorm:"column:members;not null" json:"members"`
	Status     string    `gorm:"column:status;not null" json:"status"`
	Pubkey     string    `gorm:"column:pubkey;not null" json:"pubkey"`
	CreateTime time.Time `gorm:"column:create_time" json:"create_time"`
}

// TableName MultisigAccount's table name
func (*MultisigAccount) TableName() string {
	return TableNameMultisigAccount
}
