// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePendingTransaction = "pending_transaction"

// PendingTransaction mapped from table <pending_transaction>
type PendingTransaction struct {
	ID            string    `gorm:"column:id;primaryKey" json:"id"`
	WalletAddress string    `gorm:"column:wallet_address;not null" json:"wallet_address"`
	Sequence      string    `gorm:"column:sequence" json:"sequence"`
	TxContent     string    `gorm:"column:tx_content;not null" json:"tx_content"`
	Signatures    string    `gorm:"column:signatures" json:"signatures"`
	CreateTime    time.Time `gorm:"column:create_time;not null" json:"create_time"`
	Memo          string    `gorm:"column:memo" json:"memo"`
	Deleted       int32     `gorm:"column:deleted" json:"deleted"`
}

// TableName PendingTransaction's table name
func (*PendingTransaction) TableName() string {
	return TableNamePendingTransaction
}
