// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStakingPercentage = "staking_percentage"

// StakingPercentage mapped from table <staking_percentage>
type StakingPercentage struct {
	Date      time.Time `gorm:"column:date;primaryKey" json:"date"`
	Point     string    `gorm:"column:point;primaryKey" json:"point"`
	Value     int64     `gorm:"column:value" json:"value"`
	ChainName string    `gorm:"column:chain_name;primaryKey" json:"chain_name"`
}

// TableName StakingPercentage's table name
func (*StakingPercentage) TableName() string {
	return TableNameStakingPercentage
}
