// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTopUndelegation = "top_undelegation"

// TopUndelegation mapped from table <top_undelegation>
type TopUndelegation struct {
	Delegator   string    `gorm:"column:delegator;primaryKey" json:"delegator"`
	Validator   string    `gorm:"column:validator;primaryKey" json:"validator"`
	Amount      int64     `gorm:"column:amount" json:"amount"`
	ReleaseTime time.Time `gorm:"column:release_time;not null" json:"release_time"`
	ChainName   string    `gorm:"column:chain_name;primaryKey" json:"chain_name"`
}

// TableName TopUndelegation's table name
func (*TopUndelegation) TableName() string {
	return TableNameTopUndelegation
}
