// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTopDelegation = "top_delegation"

// TopDelegation mapped from table <top_delegation>
type TopDelegation struct {
	Delegator string `gorm:"column:delegator;primaryKey" json:"delegator"`
	Amount    int64  `gorm:"column:amount" json:"amount"`
	ChainName string `gorm:"column:chain_name;primaryKey" json:"chain_name"`
	Validator string `gorm:"column:validator;primaryKey" json:"validator"`
}

// TableName TopDelegation's table name
func (*TopDelegation) TableName() string {
	return TableNameTopDelegation
}
