// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/0311xuyang/chain-util/dal/model"
)

func newMultisigAccount(db *gorm.DB, opts ...gen.DOOption) multisigAccount {
	_multisigAccount := multisigAccount{}

	_multisigAccount.multisigAccountDo.UseDB(db, opts...)
	_multisigAccount.multisigAccountDo.UseModel(&model.MultisigAccount{})

	tableName := _multisigAccount.multisigAccountDo.TableName()
	_multisigAccount.ALL = field.NewAsterisk(tableName)
	_multisigAccount.Address = field.NewString(tableName, "address")
	_multisigAccount.Name = field.NewString(tableName, "name")
	_multisigAccount.Threshold = field.NewInt32(tableName, "threshold")
	_multisigAccount.ChainName = field.NewString(tableName, "chain_name")
	_multisigAccount.Members = field.NewString(tableName, "members")
	_multisigAccount.Status = field.NewString(tableName, "status")
	_multisigAccount.Pubkey = field.NewString(tableName, "pubkey")
	_multisigAccount.CreateTime = field.NewTime(tableName, "create_time")

	_multisigAccount.fillFieldMap()

	return _multisigAccount
}

type multisigAccount struct {
	multisigAccountDo

	ALL        field.Asterisk
	Address    field.String
	Name       field.String
	Threshold  field.Int32
	ChainName  field.String
	Members    field.String
	Status     field.String
	Pubkey     field.String
	CreateTime field.Time

	fieldMap map[string]field.Expr
}

func (m multisigAccount) Table(newTableName string) *multisigAccount {
	m.multisigAccountDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m multisigAccount) As(alias string) *multisigAccount {
	m.multisigAccountDo.DO = *(m.multisigAccountDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *multisigAccount) updateTableName(table string) *multisigAccount {
	m.ALL = field.NewAsterisk(table)
	m.Address = field.NewString(table, "address")
	m.Name = field.NewString(table, "name")
	m.Threshold = field.NewInt32(table, "threshold")
	m.ChainName = field.NewString(table, "chain_name")
	m.Members = field.NewString(table, "members")
	m.Status = field.NewString(table, "status")
	m.Pubkey = field.NewString(table, "pubkey")
	m.CreateTime = field.NewTime(table, "create_time")

	m.fillFieldMap()

	return m
}

func (m *multisigAccount) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *multisigAccount) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 8)
	m.fieldMap["address"] = m.Address
	m.fieldMap["name"] = m.Name
	m.fieldMap["threshold"] = m.Threshold
	m.fieldMap["chain_name"] = m.ChainName
	m.fieldMap["members"] = m.Members
	m.fieldMap["status"] = m.Status
	m.fieldMap["pubkey"] = m.Pubkey
	m.fieldMap["create_time"] = m.CreateTime
}

func (m multisigAccount) clone(db *gorm.DB) multisigAccount {
	m.multisigAccountDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m multisigAccount) replaceDB(db *gorm.DB) multisigAccount {
	m.multisigAccountDo.ReplaceDB(db)
	return m
}

type multisigAccountDo struct{ gen.DO }

func (m multisigAccountDo) Debug() *multisigAccountDo {
	return m.withDO(m.DO.Debug())
}

func (m multisigAccountDo) WithContext(ctx context.Context) *multisigAccountDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m multisigAccountDo) ReadDB() *multisigAccountDo {
	return m.Clauses(dbresolver.Read)
}

func (m multisigAccountDo) WriteDB() *multisigAccountDo {
	return m.Clauses(dbresolver.Write)
}

func (m multisigAccountDo) Session(config *gorm.Session) *multisigAccountDo {
	return m.withDO(m.DO.Session(config))
}

func (m multisigAccountDo) Clauses(conds ...clause.Expression) *multisigAccountDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m multisigAccountDo) Returning(value interface{}, columns ...string) *multisigAccountDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m multisigAccountDo) Not(conds ...gen.Condition) *multisigAccountDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m multisigAccountDo) Or(conds ...gen.Condition) *multisigAccountDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m multisigAccountDo) Select(conds ...field.Expr) *multisigAccountDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m multisigAccountDo) Where(conds ...gen.Condition) *multisigAccountDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m multisigAccountDo) Order(conds ...field.Expr) *multisigAccountDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m multisigAccountDo) Distinct(cols ...field.Expr) *multisigAccountDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m multisigAccountDo) Omit(cols ...field.Expr) *multisigAccountDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m multisigAccountDo) Join(table schema.Tabler, on ...field.Expr) *multisigAccountDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m multisigAccountDo) LeftJoin(table schema.Tabler, on ...field.Expr) *multisigAccountDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m multisigAccountDo) RightJoin(table schema.Tabler, on ...field.Expr) *multisigAccountDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m multisigAccountDo) Group(cols ...field.Expr) *multisigAccountDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m multisigAccountDo) Having(conds ...gen.Condition) *multisigAccountDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m multisigAccountDo) Limit(limit int) *multisigAccountDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m multisigAccountDo) Offset(offset int) *multisigAccountDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m multisigAccountDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *multisigAccountDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m multisigAccountDo) Unscoped() *multisigAccountDo {
	return m.withDO(m.DO.Unscoped())
}

func (m multisigAccountDo) Create(values ...*model.MultisigAccount) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m multisigAccountDo) CreateInBatches(values []*model.MultisigAccount, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m multisigAccountDo) Save(values ...*model.MultisigAccount) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m multisigAccountDo) First() (*model.MultisigAccount, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MultisigAccount), nil
	}
}

func (m multisigAccountDo) Take() (*model.MultisigAccount, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MultisigAccount), nil
	}
}

func (m multisigAccountDo) Last() (*model.MultisigAccount, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MultisigAccount), nil
	}
}

func (m multisigAccountDo) Find() ([]*model.MultisigAccount, error) {
	result, err := m.DO.Find()
	return result.([]*model.MultisigAccount), err
}

func (m multisigAccountDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MultisigAccount, err error) {
	buf := make([]*model.MultisigAccount, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m multisigAccountDo) FindInBatches(result *[]*model.MultisigAccount, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m multisigAccountDo) Attrs(attrs ...field.AssignExpr) *multisigAccountDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m multisigAccountDo) Assign(attrs ...field.AssignExpr) *multisigAccountDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m multisigAccountDo) Joins(fields ...field.RelationField) *multisigAccountDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m multisigAccountDo) Preload(fields ...field.RelationField) *multisigAccountDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m multisigAccountDo) FirstOrInit() (*model.MultisigAccount, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MultisigAccount), nil
	}
}

func (m multisigAccountDo) FirstOrCreate() (*model.MultisigAccount, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MultisigAccount), nil
	}
}

func (m multisigAccountDo) FindByPage(offset int, limit int) (result []*model.MultisigAccount, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m multisigAccountDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m multisigAccountDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m multisigAccountDo) Delete(models ...*model.MultisigAccount) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *multisigAccountDo) withDO(do gen.Dao) *multisigAccountDo {
	m.DO = *do.(*gen.DO)
	return m
}
