// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/0311xuyang/chain-util/dal/model"
)

func newStakingPercentage(db *gorm.DB, opts ...gen.DOOption) stakingPercentage {
	_stakingPercentage := stakingPercentage{}

	_stakingPercentage.stakingPercentageDo.UseDB(db, opts...)
	_stakingPercentage.stakingPercentageDo.UseModel(&model.StakingPercentage{})

	tableName := _stakingPercentage.stakingPercentageDo.TableName()
	_stakingPercentage.ALL = field.NewAsterisk(tableName)
	_stakingPercentage.Date = field.NewTime(tableName, "date")
	_stakingPercentage.Point = field.NewString(tableName, "point")
	_stakingPercentage.Value = field.NewInt64(tableName, "value")
	_stakingPercentage.ChainName = field.NewString(tableName, "chain_name")

	_stakingPercentage.fillFieldMap()

	return _stakingPercentage
}

type stakingPercentage struct {
	stakingPercentageDo

	ALL       field.Asterisk
	Date      field.Time
	Point     field.String
	Value     field.Int64
	ChainName field.String

	fieldMap map[string]field.Expr
}

func (s stakingPercentage) Table(newTableName string) *stakingPercentage {
	s.stakingPercentageDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s stakingPercentage) As(alias string) *stakingPercentage {
	s.stakingPercentageDo.DO = *(s.stakingPercentageDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *stakingPercentage) updateTableName(table string) *stakingPercentage {
	s.ALL = field.NewAsterisk(table)
	s.Date = field.NewTime(table, "date")
	s.Point = field.NewString(table, "point")
	s.Value = field.NewInt64(table, "value")
	s.ChainName = field.NewString(table, "chain_name")

	s.fillFieldMap()

	return s
}

func (s *stakingPercentage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *stakingPercentage) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 4)
	s.fieldMap["date"] = s.Date
	s.fieldMap["point"] = s.Point
	s.fieldMap["value"] = s.Value
	s.fieldMap["chain_name"] = s.ChainName
}

func (s stakingPercentage) clone(db *gorm.DB) stakingPercentage {
	s.stakingPercentageDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s stakingPercentage) replaceDB(db *gorm.DB) stakingPercentage {
	s.stakingPercentageDo.ReplaceDB(db)
	return s
}

type stakingPercentageDo struct{ gen.DO }

func (s stakingPercentageDo) Debug() *stakingPercentageDo {
	return s.withDO(s.DO.Debug())
}

func (s stakingPercentageDo) WithContext(ctx context.Context) *stakingPercentageDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s stakingPercentageDo) ReadDB() *stakingPercentageDo {
	return s.Clauses(dbresolver.Read)
}

func (s stakingPercentageDo) WriteDB() *stakingPercentageDo {
	return s.Clauses(dbresolver.Write)
}

func (s stakingPercentageDo) Session(config *gorm.Session) *stakingPercentageDo {
	return s.withDO(s.DO.Session(config))
}

func (s stakingPercentageDo) Clauses(conds ...clause.Expression) *stakingPercentageDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s stakingPercentageDo) Returning(value interface{}, columns ...string) *stakingPercentageDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s stakingPercentageDo) Not(conds ...gen.Condition) *stakingPercentageDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s stakingPercentageDo) Or(conds ...gen.Condition) *stakingPercentageDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s stakingPercentageDo) Select(conds ...field.Expr) *stakingPercentageDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s stakingPercentageDo) Where(conds ...gen.Condition) *stakingPercentageDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s stakingPercentageDo) Order(conds ...field.Expr) *stakingPercentageDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s stakingPercentageDo) Distinct(cols ...field.Expr) *stakingPercentageDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s stakingPercentageDo) Omit(cols ...field.Expr) *stakingPercentageDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s stakingPercentageDo) Join(table schema.Tabler, on ...field.Expr) *stakingPercentageDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s stakingPercentageDo) LeftJoin(table schema.Tabler, on ...field.Expr) *stakingPercentageDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s stakingPercentageDo) RightJoin(table schema.Tabler, on ...field.Expr) *stakingPercentageDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s stakingPercentageDo) Group(cols ...field.Expr) *stakingPercentageDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s stakingPercentageDo) Having(conds ...gen.Condition) *stakingPercentageDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s stakingPercentageDo) Limit(limit int) *stakingPercentageDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s stakingPercentageDo) Offset(offset int) *stakingPercentageDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s stakingPercentageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *stakingPercentageDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s stakingPercentageDo) Unscoped() *stakingPercentageDo {
	return s.withDO(s.DO.Unscoped())
}

func (s stakingPercentageDo) Create(values ...*model.StakingPercentage) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s stakingPercentageDo) CreateInBatches(values []*model.StakingPercentage, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s stakingPercentageDo) Save(values ...*model.StakingPercentage) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s stakingPercentageDo) First() (*model.StakingPercentage, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakingPercentage), nil
	}
}

func (s stakingPercentageDo) Take() (*model.StakingPercentage, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakingPercentage), nil
	}
}

func (s stakingPercentageDo) Last() (*model.StakingPercentage, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakingPercentage), nil
	}
}

func (s stakingPercentageDo) Find() ([]*model.StakingPercentage, error) {
	result, err := s.DO.Find()
	return result.([]*model.StakingPercentage), err
}

func (s stakingPercentageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.StakingPercentage, err error) {
	buf := make([]*model.StakingPercentage, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s stakingPercentageDo) FindInBatches(result *[]*model.StakingPercentage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s stakingPercentageDo) Attrs(attrs ...field.AssignExpr) *stakingPercentageDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s stakingPercentageDo) Assign(attrs ...field.AssignExpr) *stakingPercentageDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s stakingPercentageDo) Joins(fields ...field.RelationField) *stakingPercentageDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s stakingPercentageDo) Preload(fields ...field.RelationField) *stakingPercentageDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s stakingPercentageDo) FirstOrInit() (*model.StakingPercentage, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakingPercentage), nil
	}
}

func (s stakingPercentageDo) FirstOrCreate() (*model.StakingPercentage, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.StakingPercentage), nil
	}
}

func (s stakingPercentageDo) FindByPage(offset int, limit int) (result []*model.StakingPercentage, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s stakingPercentageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s stakingPercentageDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s stakingPercentageDo) Delete(models ...*model.StakingPercentage) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *stakingPercentageDo) withDO(do gen.Dao) *stakingPercentageDo {
	s.DO = *do.(*gen.DO)
	return s
}
